### PR TITLE
NXP-21386 Specify multi-tenant modules version for release

### PR DESCRIPTION
**Pull request by egiuly-nuxeo**

### CODE REVIEW

**Review by atchertchian — CHANGES_REQUESTED** [review]
i'd be more in favour of hardcoding this in the multi-tenant module parent pom (and revert if after the release), wdyt?

**Comment by troger** [comment]
Not sure extracting a `dependencyManagement` for 2 dependencies to fix versions, and then revert it on the next commit is really usefull 🤔

**Comment by atchertchian** [comment]
sorry, got confused, thought this was a diff on the addons parent pom :+1:

**Review by atchertchian — APPROVED** [review]

**Comment by troger** [comment]
:+1:

**Pull request merged**
